FROM demoregistry.dataman-inc.com/srypoc/registry:2.3.0

MAINTAINER weitao zhou <wtzhou@dataman-inc.com>

ADD ./config.yml /etc/registry/config.yml
ADD ./private_key.pem /etc/registry/private_key.pem
ADD ./root.crt /etc/registry/root.crt
